# Generated by Django 3.2.5 on 2021-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=7, unique=True, verbose_name='Reg No:')),
                ('description', models.TextField(help_text='Enter some information about the car', max_length='1000')),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(help_text='Enter a car make. (e.g. Toyota, Honda...)', max_length=200, verbose_name='Make')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(help_text='Enter a car model. (e.g. Corolla, Demio...)', max_length=200, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(help_text='Enter the desired car type. (e.g. SUV, Saloon...)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this car in the entire listing', primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=500)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintenance')], default='a', help_text='Car Availability', max_length=1)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.car')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_make',
            field=models.ForeignKey(help_text='Choose a make for this car', on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carmake'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(help_text='Choose a model for this car', on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(help_text='Choose a type for this car', on_delete=django.db.models.deletion.RESTRICT, to='carlisting.cartype'),
        ),
    ]
