# Generated by Django 3.2.6 on 2021-10-08 09:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please enter first name', max_length=15, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Please enter last name', max_length=15, verbose_name='Last Name')),
                ('national_id_number', models.CharField(help_text='Please enter National ID number', max_length=8, unique=True, verbose_name='National ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Please enter phone number', max_length=128, region=None, unique=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.RenameField(
            model_name='carinstance',
            old_name='details',
            new_name='imprint',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carmake'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carlisting.cartype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(help_text='Some additional info about the car', max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration',
            field=models.CharField(max_length=7, unique=True, verbose_name='Reg No.'),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='car_make',
            field=models.CharField(help_text='Please enter car make (e.g. Toyota, Nissan...)', max_length=200, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_model',
            field=models.CharField(help_text='Please enter car model (e.g. Corolla, Sunny...)', max_length=200, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='car_type',
            field=models.CharField(help_text='Please enter car type (e.g. SUV, Saloon...)', max_length=200),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carowner'),
        ),
    ]
