# Generated by Django 3.2.6 on 2021-10-01 05:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0003_rename_details_carinstance_imprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please enter first name', max_length=15, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Please enter last name', max_length=15, verbose_name='Last Name')),
                ('national_id_number', models.CharField(help_text='Please enter National ID number', max_length=8, unique=True, verbose_name='National ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Please enter phone number', max_length=128, region=None, unique=True, verbose_name='Phone Number')),
            ],
        ),
    ]
