# Generated by Django 3.2.6 on 2021-10-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0004_carowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.car'),
        ),
    ]
