# Generated by Django 3.2.6 on 2021-10-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0005_carowner_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='car_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carowner'),
        ),
    ]
