# Generated by Django 3.2.6 on 2021-10-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0007_auto_20211001_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
