# Generated by Django 3.2.6 on 2021-10-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0008_auto_20211001_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
