# Generated by Django 3.2.6 on 2021-10-01 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0009_auto_20211001_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.car')),
            ],
        ),
    ]
