# Generated by Django 3.2.6 on 2021-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0010_auto_20211001_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, editable=False, upload_to=''),
        ),
    ]
